version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - "12181:12181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:12181
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092

  mongo:
    image: mongo

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"

  kafka-producer:
    build:
      context: kafka-producer
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/companies
    depends_on:
      - kafka
      - mongo

  kafka-stream:
    build:
      context: kafka-stream
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/actions?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    depends_on:
      - kafka
      - kafka-producer
      - mysql
