version: '2'
services:
  zookeeper-1:
    image: confluentinc cp zookeeper:latest
    hostname: zookeeper-1
    ports:
      - "12181:12181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
  kafka-1:
    image: confluentinc cp kafka:latest
    hostname: kafka-1
    ports:
      - "19092:19092"
  depends_on:
    - zookeeper-1
  environment:
    KAFKA_BROKER_ID: 1
    KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092

  mongo:
    image: mongo
  mysql:
    image: mysql

  kafka-producer:
    image: kafka-producer
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  kafka-stream:
    image: kafka-stream
    ports:
      - "8081:8080"
    depends_on:
      - mysql
